### ISSUE TITLE
Why it might not be showing up in A1111

### ISSUE THREAD

**Issue by duskfallcrew** [834t/sd-a1111-b34t-emblab#2]
*** Error executing callback ui_tabs_callback for /workspace/stable-diffusion-webui/extensions/sd-a1111-b34t-emblab/scripts/emblab_editor.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui/modules/script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "/workspace/stable-diffusion-webui/extensions/sd-a1111-b34t-emblab/scripts/emblab_editor.py", line 410, in add_tab
        determine_embedding_distribution()
      File "/workspace/stable-diffusion-webui/extensions/sd-a1111-b34t-emblab/scripts/emblab_editor.py", line 89, in determine_embedding_distribution
        embedding_layer = cond_model.wrapped.transformer.text_model.embeddings
      File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'Module' object has no attribute 'transformer'

**Comment by captainzero93** [comment]
I fixed a bunch of stuff, this plugin should work now, it still doesnt support SDXL, but will load regardless
